### ISSUE TITLE
Custom commands don't work

### ISSUE THREAD

**Issue by AtmanActive** [SR-G/sleep-on-lan#2] opened 2016-02-27 12:05 UTC
sol.exe 1.0.1 on windows 7 x64 SP1

I have tried everything, but I simply can't make custom commands work.

If I remove the section '"Commands" : [ { "Operation" : "halt", "Command" :"..." } ]', then going through the REST interface I can issue the 'sleep' command and sol.exe will execute it.

If I add that section, sol.exe does recognize that command by showing information about it in the REST XML output. I also can issue that URL, and sol.exe responds with 'Executing operation [halt]', but nothing happens. Nothing is executed whatsoever.

I have tried with simple notepad.exe, copying it to sol.exe's folder and with relative paths, also with slashes instead of backslashes - nothing.

No go.

**Comment by AtmanActive** [comment] 2016-02-28 15:26
Just to confirm, for my use case, sleep is useless.

Kids left 'Lego Marvel' on pause, TV got turned OFF, MikroTik sent REST sleep command, the machine went to sleep, but a day later when we wanted it back on, we were greeted with a lovely 'Lego Marvel has stopped working' window.

So, this usage scenario 'windows as a console' really needs shutdown, not sleep.

Thanks.

**Comment by AtmanActive** [comment] 2016-02-29 00:44
New debug info:

Custom commands DO work when I start sol.exe from command prompt.
Custom commands DO NOT work when sol.exe runs as a service via NSSM (privileges?).

Hope this helps.

**Comment by AtmanActive** [comment] 2016-02-29 08:45
Yup, this solves it for me:
Completely removed NSSM and service mode, created a shortcut to sol.exe with shortcut properties 'run minimized' and copied that shortcut to StartUp.

Note, however that this workaround doesn't make UDP magic packet work.
What is working: REST interface, custom commands.

Thanks.

**Comment by SR-G** [comment] 2017-11-15 20:45
Pretty sure the problem is about the current directory, once executed through a service, the current path is probably elsewhere, and thus the default JSON config (stored next to the sol.exe binary) is not found (the program just use its default configuration in that situation). Don't know if i can do anything about this when using it as a service. 

Your workaround is probably the best, closing the issue for the now.

**Closed by SR-G** 2017-11-15 20:45 UTC

**Comment by yeralin** [comment] 2017-11-27 05:10
@SR-G Not really. Having the same issue. JSON config gets picked up (changing `HTTP:<port>` actually affects server's port at start), but halt command doesn't work unfortunately.

![image](https://user-images.githubusercontent.com/8620461/33251756-246fd2e4-d307-11e7-85cd-9dcf342752d3.png)

Hitting `http://192.168.1.2:8007/halt`, just returns:
`<result>
<application>sleep-on-lan</application>
<hosts>
<host ip="0.0.0.0" mac="00:ff:19:44:3e:9f"/>
<host ip="192.168.1.2" mac="d8:50:e6:41:03:8d"/>
</hosts>
<listeners>
<listener type="UDP" port="9" active="true"/>
<listener type="UDP" port="7" active="true"/>
<listener type="HTTP" port="8007" active="true"/>
</listeners>
</result>`

**Comment by SR-G** [comment] 2017-11-27 07:14
Can you try with the latest 1.0.2-SNAPSHOT version ? https://github.com/SR-G/sleep-on-lan/releases
Obviously commands are not read, based on your start logs. Either you have an old version (there should be both some informations about the configuration file used, and read commands should be displayed in the start logs), either there is something wrong with the JSON configuration (but at first glance i don't see what could be wrong).

**Comment by yeralin** [comment] 2017-11-28 03:56
@SR-G Oh, you are right. I was using 1.0.0 mentioned in README.md haha. 

Just a suggestion, you could just give a link to https://github.com/SR-G/sleep-on-lan/releases page.

**Comment by SR-G** [comment] 2017-11-28 11:36
Good point indeed, corrected.
