### ISSUE TITLE
Custom commands don't work in linux

### ISSUE THREAD

**Issue by keytor** [SR-G/sleep-on-lan#5] opened 2016-12-10 11:27 UTC
Hi, I'm configuring sleep-on-lan for halt the system and I write this in the sol.json:

{
  "Listeners" : ["UDP:9", "UDP:7", "HTTP:8009" ],
  "LogLevel" : "INFO",
  "Commands" : [
    {
        "Operation" : "poweroff",
        "Command" : "poweroff"
    }]
}

I try this configuration and don't work too:
{
  "Listeners" : ["UDP:9", "UDP:7", "HTTP:8009" ],
  "LogLevel" : "INFO",
  "Commands" : [
    {
        "Operation" : "halt",
        "Command" : "pm-halt"
    }]
}

The log:
INFO: 2016/12/10 12:18:07 sol.go:19: Now starting sleep-on-lan, hardware IP/mac addresses are :
INFO: 2016/12/10 12:18:07 sol.go:21:  - local IP adress [127.0.0.1/8], mac []
INFO: 2016/12/10 12:18:07 sol.go:21:  - local IP adress [::1/128], mac []
INFO: 2016/12/10 12:18:07 sol.go:21:  - local IP adress [192.168.1.XXX/24], mac [aa:aa:aa:aa:aa:aa]
INFO: 2016/12/10 12:18:07 sol.go:21:  - local IP adress [172.17.0.1/16], mac [aa:aa:aa:aa:aa:aa]
INFO: 2016/12/10 12:18:07 listener_udp.go:13: Now listening UDP packets on port [9]
INFO: 2016/12/10 12:18:07 listener_udp.go:13: Now listening UDP packets on port [7]
INFO: 2016/12/10 12:18:07 listener_http.go:126: Now listening HTTP on port [8009], urls will be :
INFO: 2016/12/10 12:18:07 listener_http.go:129:  - http://192.168.1.XXX:8009/sleep
INFO: 2016/12/10 12:18:07 listener_http.go:129:  - http://192.168.1.XXX:8009/wol/[A-z]+
INFO: 2016/12/10 12:18:07 listener_http.go:129:  - http://192.168.1.XXX:8009/

Ther are any problem with json configuration?

Many Thanks

**Comment by SR-G** [comment] 2017-11-15 20:41
As far as i can tell, it's (was ?) working, as long as you have the "sol.json" file in the same folder than the binary (i should see for adding a --config parameter, by the way).

With your configuration and current code i get : 

```
INFO: 2017/11/15 20:40:31 sol.go:20: Application [sleep-on-lan version 1.0.0-SNAPSHOT "FIRST_ITERATION"]
INFO: 2017/11/15 20:40:31 sol.go:21: Loaded configuration from [/go/src/sol.json]
INFO: 2017/11/15 20:40:31 sol.go:23: Now starting sleep-on-lan, hardware IP/mac addresses are : 
INFO: 2017/11/15 20:40:31 sol.go:25:  - local IP adress [127.0.0.1/8], mac []
INFO: 2017/11/15 20:40:31 sol.go:25:  - local IP adress [172.17.0.16/16], mac [02:42:ac:11:00:10]
INFO: 2017/11/15 20:40:31 sol.go:28: Available commands are : 
INFO: 2017/11/15 20:40:31 sol.go:30:  - operation [poweroff], command [poweroff], default [true], type []
INFO: 2017/11/15 20:40:31 listener_http.go:70: Registering route [/]
INFO: 2017/11/15 20:40:31 listener_http.go:70: Registering route [/poweroff]
INFO: 2017/11/15 20:40:31 listener_http.go:70: Registering route [/quit]
INFO: 2017/11/15 20:40:31 listener_http.go:70: Registering route [/wol/:mac]

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.2.3
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
INFO: 2017/11/15 20:40:31 listener_udp.go:12: Now listening UDP packets on port [9]
⇨ http server started on [::]:8009
INFO: 2017/11/15 20:40:31 listener_udp.go:12: Now listening UDP packets on port [7]

root@6741062f3330:/go/src# 
root@6741062f3330:/go/src# curl localhost:8009/poweroff
INFO: 2017/11/15 20:40:38 listener_http.go:131: Executing [poweroff]
INFO: 2017/11/15 20:40:38 sleeper_linux.go:9: Executing operation [poweroff], type [poweroff], command [poweroff]
INFO: 2017/11/15 20:40:38 sleeper_linux.go:17: Sleep implementation [linux], sleep command is [poweroff]
ERROR: 2017/11/15 20:40:38 sleeper_linux.go:20: Can't execute command [poweroff] : exec: "poweroff": executable file not found in $PATH
```

**Comment by lkd70** [comment] 2017-11-16 20:05
Hello, it'd seem I'm having the same issue, just tried this out on my linux-mint machine

Configuration (`~/Desktop/SoL/linux/sol.json`):
```
{
    "Listeners": [
        "UDP:9",
        "HTTP:8009"
    ],
    "LogLevel": "DEBUG",
    "BroadcastIP": "255.255.255.255",
    "Commands": [
        {
            "Operation": "nap",
            "Command": "pm-suspend",
            "Default": "false"
        }
    ]
}
```

Upon running the 'nap' command (I created this just for test purposes...) I don't see any result from the back-end (`sudo ~/Desktop/SoL/linux/sol` `http://localhost:8009/nap/`): 

```
INFO: 2017/11/16 19:53:13 sol.go:19: Now starting sleep-on-lan, hardware IP/mac addresses are : 
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [xxxx:xxxx:xxxx:xxxx:xx/64], mac [xx:xx:xx:xx:xx:xx]
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [xxxx:xxxx:xxxx:xxxx:xx/64], mac [xx:xx:xx:xx:xx:xx]
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [127.0.0.1/8], mac []
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [::1/128], mac []
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [192.168.1.99/24], mac [xx:xx:xx:xx:xx:xx]
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [xxxx:xxxx:xxxx:xxxx:xx/64], mac [xx:xx:xx:xx:xx:xx]
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [172.17.0.1/16], mac [xx:xx:xx:xx:xx:xx]
INFO: 2017/11/16 19:53:13 sol.go:21:  - local IP adress [xxxx:xxxx:xxxx:xxxx:xx/64], mac [xx:xx:xx:xx:xx:xx]
INFO: 2017/11/16 19:53:13 listener_udp.go:13: Now listening UDP packets on port [9]
INFO: 2017/11/16 19:53:13 listener_http.go:126: Now listening HTTP on port [8009], urls will be : 
INFO: 2017/11/16 19:53:13 listener_http.go:129:  - http://192.168.1.99:8009/sleep
INFO: 2017/11/16 19:53:13 listener_http.go:129:  - http://192.168.1.99:8009/wol/[A-z]+
INFO: 2017/11/16 19:53:13 listener_http.go:129:  - http://192.168.1.99:8009/
```

Yes, this is after running the command through HTTP. Browser side, I get the usual XML result:
```
<result>
	<application>sleep-on-lan</application>
	<hosts>
		<host ip="xxxx::xxxx:xxxx:xxxx:xx/64" mac="xx:xx:xx:xx:xx:xx"/>
		<host ip="127.0.0.1/8" mac=""/>
		<host ip="::1/128" mac=""/>
		<host ip="192.168.1.99/24" mac="xx:xx:xx:xx:xx:xx"/>
		<host ip="xxxx::xxxx:xxxx:xxxx:xxxx/64" mac="xx:xx:xx:xx:xx:xx"/>
		<host ip="172.17.0.1/16" mac="xx:xx:xx:xx:xx:xx"/>
		<host ip="xxxx::xx:xxxx:xxxx:xxxx/64" mac="xx:xx:xx:xx:xx:xx"/>
		<host ip="xxxx::xxxx:xxxx:xxxx:xxxx/64" mac="xx:xx:xx:xx:xx:xx"/>
	</hosts>
	<listeners>
		<listener active="true" port="9" type="UDP"/>
		<listener active="true" port="8009" type="HTTP"/>
	</listeners>
</result>
```

If there's any additional information you'd like, please ask.

**Comment by SR-G** [comment] 2017-11-16 20:59
Two questions (to try to understand) (i'll add additional logs anyway) : is you sol binary in the same folder than sol.json ? And are you running the sol binary from this folder or through an absolute (or even relative path other than "./") ?

**Comment by lkd70** [comment] 2017-11-16 21:18
1. The sol.json file is in the same directory as the sol file
2. I have tried both ./sol as it was convenient, and the absolute path.

**Comment by SR-G** [comment] 2017-11-16 21:41
Can you try with the latest SNAPSHOT 1.0.2 ? I'm surprised to not see any logs about configuration loading on your side (telling which file is used (if any) or that configuration is not found) (logs were already in place). On my side, whatever the situation (linux with absolute or relative path, windows, ...) i still have the logs.

https://github.com/SR-G/sleep-on-lan/releases/tag/1.0.2-SNAPSHOT

**Comment by lkd70** [comment] 2017-11-16 21:54
It'd seem I've encountered a new issue with your pre-release, that being it won't even recognize the file:

![image](https://user-images.githubusercontent.com/7032715/32917948-a053661a-cb18-11e7-9b2e-3fdefd8f1021.png)

**Comment by SR-G** [comment] 2017-11-16 22:00
My bad ! Have compiled it inside an alpine linux docker container, forgot to add the proper compilation flags. New SNAPSHOT just uploaded should be ok (tested additionnaly on standard amd64 archlinux on my side this time).

Github SNAPSHOT is the same but zip content generated on 22:57 : https://github.com/SR-G/sleep-on-lan/releases/tag/1.0.2-SNAPSHOT

**Comment by lkd70** [comment] 2017-11-16 22:07
That appears to have fixed the issue, it now reports that I'm using the json file and correctly implements the command as intended. Thank you!
I'm sure I'll break something again soon, though. Stand-by!

**Comment by SR-G** [comment] 2017-11-16 22:10
Thanks for the test and confirmation.

Closing the issue for now, feel free to re-open if needed.

**Closed by SR-G** 2017-11-16 22:10 UTC
