### ISSUE TITLE
Does it still work on Linux?

### ISSUE THREAD

**Issue by ArtemeeSenin** [SR-G/sleep-on-lan#24] opened 2020-03-28 23:26 UTC
Hello! Thank you for your work on this project!

I have tried to run it on Ubuntu Server 18.04, but it does not seem to work. Even logs are empty.
I tries to run it by command from example
```
sudo setcap 'cap_net_bind_service=+ep' /path/to/sol_binary
nohup /path/to/sol_binary > /var/log/sleep-on-lan.log 2>&1 &
```
Through `ps aux` I see that this sol process is running and by `tcpdump` I see that packets are captured by NIC. But no logs from sol binary are presend and pc is not put into sleep.

Possibly I did something wrong or should I recompile this first if it could help?

**Comment by SR-G** [comment] 2020-03-29 21:13
Hello. I'll try to see if i can test it on Ubuntu (but it's a bit difficult to test, pragmatically speaking !)
At first glance your commands seem fine. You should at least have logs, but maybe you can change the log level in the JSON configuration file (to be switched as DEBUG).

```json
{
  "Listeners" : ["UDP:9", "HTTP:8009" ],
  "LogLevel" : "INFO",
  "BroadcastIP" : "255.255.255.255",
  "Commands" : []
}
```

Also for test purposes you can try to reach the HTTP endpoint and/or try to adjust the commands, depending on where the issue is (either on the trigger side about UDP, either on the sleep command itself).

**Comment by SR-G** [comment] 2021-06-29 20:44
For reference, i did the test and as far i can tell, there is no issue.
I tested in a docker container with the following steps, and with or without being root.

Start the container with : 

```bash
docker run --rm --name "sleep-on-lan-test" -it --net=host ubuntu:18.04 /bin/bash
```

Inside the container : 

```bash
apt-get update && apt-get install -y wget unzip libcap2 libcap2-bin
wget "https://github.com/SR-G/sleep-on-lan/releases/download/1.0.5-RELEASE/SleepOnLAN-1.0.5-RELEASE.zip"
unzip SleepOnLAN-1.0.5-RELEASE.zip
```

Test with root : 

```
cd linux
./sol
```

Once wakeonlan is triggered from another computer, i get in the logs : 

```
INFO: 2021/06/29 20:37:32 listener_udp.go:31: Received a MAC address from IP [192.168.8.3:45187], extracted mac [bc:5f:f4:2b:df:2b]
INFO: 2021/06/29 20:37:32 listener_udp.go:33: (reversed) received MAC address match a local address
INFO: 2021/06/29 20:37:32 sleeper_linux.go:10: Executing operation [sleep], type [pm-suspend], command [pm-suspend]
``` 

Without root : 

```bash
useradd test_account
setcap 'cap_net_bind_service=+ep' ./sol
su test_account
./sol
```

(of course without setcap, it's not possible to start the process with that test account)

And same, after triggering wake-on-lan from another computer : 

```
INFO: 2021/06/29 20:40:04 listener_udp.go:15: Now listening UDP packets on port [9]
INFO: 2021/06/29 20:40:08 listener_udp.go:31: Received a MAC address from IP [192.168.8.3:42670], extracted mac [bc:5f:f4:2b:df:2b]
INFO: 2021/06/29 20:40:08 listener_udp.go:33: (reversed) received MAC address match a local address
```

So no issues for me, closing.

**Closed by SR-G** 2021-06-29 20:44 UTC
Labels: question
